# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fe6610c81b37c1c80462cc01e227db474f344f86659ef2586a49c49263b62ebf3aaf8278e97006eb6f5bbf64d56a5810fc3d937892a74374f1e0b3eaf5d51e9
  GMAIL_USERNAME: 'islam0322.@gmail.com'
  GMAIL_PASSWORD: '1151310398'
test:
  secret_key_base: 139b72268d0fbb80f8f797e1245fd9103332c837cee4ab580d7657b9094cdcb250e05339bd8f9bf92bd133efeb529969bd04cd43f90a9daf28c4203edd1fe752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
